name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # Push events to semantic-version tags, i.e. v20.15.10
    paths:
      - '.github/workflows/**.yml'
      - 'src/**'
      - 'go.*'
      - '*.go'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**.yml'
      - 'src/**'
      - 'go.*'
      - '*.go'

jobs:

  strongo_workflow:
#    permissions:
#      contents: write
    uses: strongo/cicd/.github/workflows/workflow.yml@main

    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
